repos:
- repo: https://github.com/rcmdnk/pyproject-pre-commit
  rev: v0.1.10
  hooks:
  - id: black-diff
  - id: black
  # - id: blacken-docs
  # - id: autoflake-diff
  # - id: autoflake
  # - id: autopep8-diff
  # - id: autopep8
  # - id: isort-diff
  # - id: isort
  # - id: flake8
  # - id: bandit
  # - id: mypy
  # - id: numpydoc-validation
  # - id: shellcheck
  - id: mdformat-check
  - id: mdformat
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format



ci:
  autoupdate_schedule: quarterly
