apiVersion: 1

datasources:
  - name: TemporalMetrics
    type: prometheus
    access: proxy
    url: http://temporal-prometheus:9090
    isDefault: true
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://temporal-prometheus:9090
    isDefault: false
    editable: true
    uid: prometheus

  - name: prometheus
    type: prometheus
    access: proxy
    url: http://temporal-prometheus:9090
    isDefault: false
    editable: true
    uid: prometheus-2

  - name: DS_PROMETHEUS
    type: prometheus
    access: proxy
    url: http://temporal-prometheus:9090
    isDefault: false
    editable: true
    uid: DS_PROMETHEUS
