log:
  stdout: true
  level: "debug,info"

persistence:
  defaultStore: default
  visibilityStore: visibility
  numHistoryShards: 2048
  datastores:
    default:
      sql:
        pluginName: "mysql8"
        driverName: "mysql8"
        databaseName: "temporal"
        connectAddr: "mysql:3306"
        connectProtocol: "tcp"
        user: root
        password: root
        maxConnLifetime: 1h
        maxConns: 100
        maxIdleConns: 100
        secretName: ""
    visibility:
      elasticsearch:
        version: "v7"
        url:
            scheme: "http"
            host: "elasticsearch:9200"
        username: ""
        password: ""
        logLevel: "error"
        indices:
            visibility: "temporal_visibility_v1_dev"

global:
  membership:
    name: temporal
    maxJoinDuration: 30s
    broadcastAddress: {{ default .Env.POD_IP "0.0.0.0" }}

  pprof:
    port: 7936

  metrics:
    tags:
      type: {{ .Env.SERVICES }}
    prometheus:
      timerType: histogram
      listenAddress: "0.0.0.0:9090"

services:
  frontend:
    rpc:
      grpcPort: 7233
      httpPort: 7243
      membershipPort: 6933
      bindOnIP: "0.0.0.0"
  internal-frontend:
    rpc:
      grpcPort: 7236
      httpPort: 7246
      membershipPort: 6936
      bindOnIP: "0.0.0.0"

  history:
    rpc:
      grpcPort: 7234
      membershipPort: 6934
      bindOnIP: "0.0.0.0"

  matching:
    rpc:
      grpcPort: 7235
      membershipPort: 6935
      bindOnIP: "0.0.0.0"

  worker:
    rpc:
      membershipPort: 6939
      bindOnIP: "0.0.0.0"

clusterMetadata:
  enableGlobalDomain: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "temporal-frontend"
      rpcAddress: "127.0.0.1:7233"
      httpAddress: "127.0.0.1:7243"

dcRedirectionPolicy:
  policy: "noop"
  toDC: ""

archival:
  status: "disabled"

dynamicConfigClient:
  filepath: "/etc/temporal/dynamic_config/dynamic_config.yaml"
  pollInterval: "5s"
